# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkbrr < Formula
  desc "Command-line tool for creating, modifying and inspecting torrent files"
  homepage "https://github.com/autobrr/mkbrr"
  version "1.20.0"
  license "GPL-2.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autobrr/mkbrr/releases/download/v1.20.0/mkbrr_1.20.0_darwin_x86_64.tar.gz"
      sha256 "1e622a0c3d2ae3e999b6624abd7a4d9d8a9ae241d3f8c08b7ed7dcc224632eed"

      def install
        bin.install "mkbrr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autobrr/mkbrr/releases/download/v1.20.0/mkbrr_1.20.0_darwin_arm64.tar.gz"
      sha256 "83b931a55a7c1afd5ea893abf47db777a368d40f62d406e015448b6ca66e43d9"

      def install
        bin.install "mkbrr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/autobrr/mkbrr/releases/download/v1.20.0/mkbrr_1.20.0_linux_x86_64.tar.gz"
      sha256 "4799825390a117837eec0c64550628bc2b397fa4383d5a4bcc755b89935337a1"
      def install
        bin.install "mkbrr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/autobrr/mkbrr/releases/download/v1.20.0/mkbrr_1.20.0_linux_arm.tar.gz"
      sha256 "2ef5e64663cefdb7a3c8c6225566a52fcf75673b52c84776ce44894c6af906be"
      def install
        bin.install "mkbrr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/autobrr/mkbrr/releases/download/v1.20.0/mkbrr_1.20.0_linux_arm64.tar.gz"
      sha256 "6399c450f157eba6292c40f9ac5422d437ff1cf2855fa9159a9afe9f93c43587"
      def install
        bin.install "mkbrr"
      end
    end
  end

  test do
    system "#{bin}/mkbrr", "version"
  end
end
